### ISSUE TITLE
no net/minecraft

### ISSUE THREAD

**Issue by 43ee3g** [10askinsw/Yawk-Client#1]
client won't run without the net/minecraft
optifine src: https://www.dropbox.com/s/xpgeat01igoe5hd/Optifine%20SRC.zip?dl=0

**Comment by 10askinsw** [comment]
We can't have the net/minecraft package here on github, due to copyright strikes to other repos from Mojang. Here is the source, including the net/minecraft:
https://www.mediafire.com/?iwcz2f2il231za3

We'll implement Optifine in the near future. I'll tell you when it's done.

**Comment by 43ee3g** [comment]
maybe upload full source to your site?

**Comment by 10askinsw** [comment]
That's a good idea. I'll do that.
Also, we've now implemented Optifine.

The source: http://yawk.net/downloads/YawkClient.rar
