### ISSUE TITLE
BannerLag and AntiBannerLag

### ISSUE THREAD

**Issue by 43ee3g** [10askinsw/Yawk-Client#2]
so minecraft 1.8.8 fixed the glitch where this banner laggs you
I think the server jar fixed it but the client just made it even worse.
instead of dropping your fps to 0 in 1.8.7 or less versions in 1.8.8 client instead it kicks you from the server
the code for getting one is here
https://github.com/43ee3g/Yawk-Client/blob/43ee3g-patch-1/net/yawk/client/mods/world/LagBanner.java
It would be great if you could make something that prevents you from getting lagged out by this

**Comment by 10askinsw** [comment]
I made something which seems to work, the code for the modified minecraft classes is here:
net.minecraft.item.ItemBanner: http://pastebin.com/VNb5D3h2
net.minecraft.tileentity.TileEntityBanner: http://pastebin.com/yQRasRyM
